# Auto update from Guizhan Build is enabled by default.
auto-update: true

guide:
  survival-improvements: true
  cheat-improvements: true
  survival-guide-title: "&2&lSlimefun 指南 (生存模式)         &e&l爱来自 JustEnoughGuide"
  cheat-guide-title: "&c&lSlimefun 指南 (作弊模式)         &e&l爱来自 JustEnoughGuide"

improvements:
  pinyin-search: true
  bookmark: true
  rts-search: true
  beginner-option: true

# Toggle integrations that causes lore appending.
integrations:
  ryken-slimefun-customizer: true #  Ryken Slimefun Customizer (Estimate Material Generator Production Count)
  emc-tech: true #  EMC Tech (Show EMC Value)
  final-tech-changed: true #  Final Tech (Show Item Value in Equivalent Exchange Table.)

# Do not change this value unless you know what you are doing.
config-version: 1.5

# Do not change this value unless you know what you are doing.
debug: false
