name: JustEnoughGuide-Improved
author: [balugaq, Eventually]
description: This is a Slimefun addon and improved the guide.
main: com.balugaq.jeg.implementation.JustEnoughGuide
website: https://github.com/HikariRevivalProject/JustEnoughGuide-Improved
version: ${project.version}
api-version: 1.17
depend:
  - Slimefun
  - GuizhanLibPlugin
softdepend:
  - LogiTech
  - EMCTech
  - RykenSlimefunCustomizer
  - FinalTECH-Changed
commands:
  justenoughguide:
    aliases:
      - jeg
      - justenoughguide
    description: /justenoughguide
    usage: /justenoughguide <sub>
